contact_links:
  - name: 📚 Documentation
    url: https://nuxt-themes.netlify.app
    about: Check documentation for usage
  - name: 💬 Discussions
    url: https://github.com/nuxt-themes/config/discussions
    about: Use discussions if you have an idea for improvement and asking questions
